GET http://localhost:8080/essbase/hello HTTP/1.1

###
POST http://localhost:8080/essbase/login HTTP/1.1
Content-Type: application/json

{
    "userName": "admin",
    "password": "admin123",
    "olapServerName": "ec2-3-7-12-73.ap-south-1.compute.amazonaws.com",
    "url": "http://ec2-3-7-12-73.ap-south-1.compute.amazonaws.com:28080/aps/JAPI"
}

###
GET http://localhost:8080/essbase/logout HTTP/1.1

###
GET http://localhost:8080/essbase/applications HTTP/1.1
content-type: application/json


###
GET http://localhost:8080/essbase/applications/Sample/Basic/defaultGrid HTTP/1.1
###
GET http://localhost:8080/essbase/applications/Sample/Interntl/defaultGrid HTTP/1.1


###
POST http://localhost:8080/essbase/applications/Sample/Basic/refresh HTTP/1.1
Content-Type: application/json

{
  "totalRows": 18,
  "totalCols": 5,
  "dataGrid": [
    [
      "",
      "Measures",
      "Product",
      "Market",
      "Scenario"
    ],
    [
      "Jan",
      "18024.0",
      "",
      "",
      ""
    ],
    [
      "Feb",
      "8346.0",
      "",
      "",
      ""
    ],
    [
      "Mar",
      "8333.0",
      "",
      "",
      ""
    ],
    [
      "     Qtr1",
      "24703.0",
      "",
      "",
      ""
    ],
    [
      "Apr",
      "8644.0",
      "",
      "",
      ""
    ],
    [
      "May",
      "8929.0",
      "",
      "",
      ""
    ],
    [
      "Jun",
      "9534.0",
      "",
      "",
      ""
    ],
    [
      "     Qtr2",
      "27107.0",
      "",
      "",
      ""
    ],
    [
      "Jul",
      "9878.0",
      "",
      "",
      ""
    ],
    [
      "Aug",
      "9545.0",
      "",
      "",
      ""
    ],
    [
      "Sep",
      "8489.0",
      "",
      "",
      ""
    ],
    [
      "     Qtr3",
      "27912.0",
      "",
      "",
      ""
    ],
    [
      "Oct",
      "8653.0",
      "",
      "",
      ""
    ],
    [
      "Nov",
      "8367.0",
      "",
      "",
      ""
    ],
    [
      "Dec",
      "8780.0",
      "",
      "",
      ""
    ],
    [
      "     Qtr4",
      "25800.0",
      "",
      "",
      ""
    ],
    [
      "          Year",
      "105522.0",
      "",
      "",
      ""
    ]
  ],
  "dataGridMetaData": [
    [
      2,
      0,
      0,
      0,
      0
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ],
    [
      0,
      1,
      2,
      2,
      2
    ]
  ]
}

###
POST http://localhost:8080/essbase/applications/Sample/Basic/zoomIn/0/2 HTTP/1.1
Content-Type: application/json

{
  "totalRows": 2,
  "totalCols": 5,
  "dataGrid": [
    [
      "",
      "Measures",
      "Product",
      "Market",
      "Scenario"
    ],
    [
      "Year",
      "105522.0",
      "",
      "",
      ""
    ]
  ],
  "dataGridMetaData": [
    [
      2,
      0,
      0,
      0,
      0
    ],
    [
      0,
      1,
      2,
      2,
      2
    ]
  ]
}



###
POST http://localhost:8080/essbase/applications/Sample/Basic/zoomInBottom/1/0 HTTP/1.1
Content-Type: application/json

{
  "totalRows": 2,
  "totalCols": 5,
  "dataGrid": [
    [
      "",
      "Measures",
      "Product",
      "Market",
      "Scenario"
    ],
    [
      "Year",
      "105522.0",
      "",
      "",
      ""
    ]
  ]
}

###
POST http://localhost:8080/essbase/applications/Sample/Basic/zoomInAll/1/0 HTTP/1.1
Content-Type: application/json

{
  "totalRows": 2,
  "totalCols": 5,
  "dataGrid": [
    [
      "",
      "Measures",
      "Product",
      "Market",
      "Scenario"
    ],
    [
      "Year",
      "105522.0",
      "",
      "",
      ""
    ]
  ]
}

###
POST http://35.184.51.106:8080/essbase/applications/Sample/Basic/zoomOut/1/0 HTTP/1.1
Content-Type: application/json

{
  "totalRows": 2,
  "totalCols": 5,
  "dataGrid": [
    [
      "",
      "Measures",
      "Product",
      "Market",
      "Scenario"
    ],
    [
      "Year",
      "105522.0",
      "",
      "",
      ""
    ]
  ]
}

### 
POST http://localhost:8080/essbase/applications/Sample/Basic/keepOnly  HTTP/1.1
Content-Type: application/json

{
    "totalRows": 31,
    "totalCols": 5,
    "dataGrid": [
        [
            "",
            "",
            "Measures",
            "Market",
            "Scenario"
        ],
        [
            "Colas",
            "Qtr1",
            "7048",
            "",
            ""
        ],
        [
            "Colas",
            "Qtr2",
            "7872",
            "",
            ""
        ],
        [
            "Colas",
            "Qtr3",
            "8511",
            "",
            ""
        ],
        [
            "Colas",
            "Qtr4",
            "7037",
            "",
            ""
        ],
        [
            "Colas",
            "     Year",
            "30468",
            "",
            ""
        ],
        [
            "Root Beer",
            "Qtr1",
            "6721",
            "",
            ""
        ],
        [
            "Root Beer",
            "Qtr2",
            "7030",
            "",
            ""
        ],
        [
            "Root Beer",
            "Qtr3",
            "7005",
            "",
            ""
        ],
        [
            "Root Beer",
            "Qtr4",
            "7198",
            "",
            ""
        ],
        [
            "Root Beer",
            "     Year",
            "27954",
            "",
            ""
        ],
        [
            "Cream Soda",
            "Qtr1",
            "5929",
            "",
            ""
        ],
        [
            "Cream Soda",
            "Qtr2",
            "6769",
            "",
            ""
        ],
        [
            "Cream Soda",
            "Qtr3",
            "6698",
            "",
            ""
        ],
        [
            "Cream Soda",
            "Qtr4",
            "6403",
            "",
            ""
        ],
        [
            "Cream Soda",
            "     Year",
            "25799",
            "",
            ""
        ],
        [
            "Fruit Soda",
            "Qtr1",
            "5005",
            "",
            ""
        ],
        [
            "Fruit Soda",
            "Qtr2",
            "5436",
            "",
            ""
        ],
        [
            "Fruit Soda",
            "Qtr3",
            "5698",
            "",
            ""
        ],
        [
            "Fruit Soda",
            "Qtr4",
            "5162",
            "",
            ""
        ],
        [
            "Fruit Soda",
            "     Year",
            "21301",
            "",
            ""
        ],
        [
            "Diet Drinks",
            "Qtr1",
            "7017",
            "",
            ""
        ],
        [
            "Diet Drinks",
            "Qtr2",
            "7336",
            "",
            ""
        ],
        [
            "Diet Drinks",
            "Qtr3",
            "7532",
            "",
            ""
        ],
        [
            "Diet Drinks",
            "Qtr4",
            "6941",
            "",
            ""
        ],
        [
            "Diet Drinks",
            "     Year",
            "28826",
            "",
            ""
        ],
        [
            "     Product",
            "Qtr1",
            "24703",
            "",
            ""
        ],
        [
            "     Product",
            "Qtr2",
            "27107",
            "",
            ""
        ],
        [
            "     Product",
            "Qtr3",
            "27912",
            "",
            ""
        ],
        [
            "     Product",
            "Qtr4",
            "25800",
            "",
            ""
        ],
        [
            "     Product",
            "     Year",
            "105522",
            "",
            ""
        ]
    ],
    "dataGridMetaData": [
        [
            2,
            2,
            0,
            0,
            0
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ]
    ],
    "selectedRanges": [
        [
            6,
            1,
            1,
            1
        ]
    ]
}

### 
POST http://localhost:8080/essbase/applications/Sample/Basic/removeOnly  HTTP/1.1
Content-Type: application/json

{
    "totalRows": 31,
    "totalCols": 5,
    "dataGrid": [
        [
            "",
            "",
            "Measures",
            "Market",
            "Scenario"
        ],
        [
            "Colas",
            "Qtr1",
            "7048",
            "",
            ""
        ],
        [
            "Colas",
            "Qtr2",
            "7872",
            "",
            ""
        ],
        [
            "Colas",
            "Qtr3",
            "8511",
            "",
            ""
        ],
        [
            "Colas",
            "Qtr4",
            "7037",
            "",
            ""
        ],
        [
            "Colas",
            "     Year",
            "30468",
            "",
            ""
        ],
        [
            "Root Beer",
            "Qtr1",
            "6721",
            "",
            ""
        ],
        [
            "Root Beer",
            "Qtr2",
            "7030",
            "",
            ""
        ],
        [
            "Root Beer",
            "Qtr3",
            "7005",
            "",
            ""
        ],
        [
            "Root Beer",
            "Qtr4",
            "7198",
            "",
            ""
        ],
        [
            "Root Beer",
            "     Year",
            "27954",
            "",
            ""
        ],
        [
            "Cream Soda",
            "Qtr1",
            "5929",
            "",
            ""
        ],
        [
            "Cream Soda",
            "Qtr2",
            "6769",
            "",
            ""
        ],
        [
            "Cream Soda",
            "Qtr3",
            "6698",
            "",
            ""
        ],
        [
            "Cream Soda",
            "Qtr4",
            "6403",
            "",
            ""
        ],
        [
            "Cream Soda",
            "     Year",
            "25799",
            "",
            ""
        ],
        [
            "Fruit Soda",
            "Qtr1",
            "5005",
            "",
            ""
        ],
        [
            "Fruit Soda",
            "Qtr2",
            "5436",
            "",
            ""
        ],
        [
            "Fruit Soda",
            "Qtr3",
            "5698",
            "",
            ""
        ],
        [
            "Fruit Soda",
            "Qtr4",
            "5162",
            "",
            ""
        ],
        [
            "Fruit Soda",
            "     Year",
            "21301",
            "",
            ""
        ],
        [
            "Diet Drinks",
            "Qtr1",
            "7017",
            "",
            ""
        ],
        [
            "Diet Drinks",
            "Qtr2",
            "7336",
            "",
            ""
        ],
        [
            "Diet Drinks",
            "Qtr3",
            "7532",
            "",
            ""
        ],
        [
            "Diet Drinks",
            "Qtr4",
            "6941",
            "",
            ""
        ],
        [
            "Diet Drinks",
            "     Year",
            "28826",
            "",
            ""
        ],
        [
            "     Product",
            "Qtr1",
            "24703",
            "",
            ""
        ],
        [
            "     Product",
            "Qtr2",
            "27107",
            "",
            ""
        ],
        [
            "     Product",
            "Qtr3",
            "27912",
            "",
            ""
        ],
        [
            "     Product",
            "Qtr4",
            "25800",
            "",
            ""
        ],
        [
            "     Product",
            "     Year",
            "105522",
            "",
            ""
        ]
    ],
    "dataGridMetaData": [
        [
            2,
            2,
            0,
            0,
            0
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ],
        [
            0,
            0,
            1,
            2,
            2
        ]
    ],
    "selectedRanges": [
        [
            6,
            1,
            1,
            1
        ]
    ]
}

###

POST http://localhost:8080/essbase/applications/Sample/Basic/pivot/0/2 HTTP/1.1
Content-Type: application/json

{
  "totalRows": 2,
  "totalCols": 5,
  "dataGrid": [
    [
      "",
      "Measures",
      "Product",
      "Market",
      "Scenario"
    ],
    [
      "Year",
      "105522.0",
      "",
      "",
      ""
    ]
  ],
  "dataGridMetaData": [
    [
      2,
      0,
      0,
      0,
      0
    ],
    [
      0,
      1,
      2,
      2,
      2
    ]
  ]
}

##{"totalRows":2,"totalCols":5,"dataGrid":[["","Measures","Product","Market","Scenario"],["Year","105522","","",""]],"dataGridMetaData":[[2,0,0,0,0],[0,1,2,2,2]]}

###
POST http://localhost:8080/essbase/applications/Sample/Basic/pivotToPov/1/0 HTTP/1.1
Content-Type: application/json

{
  "totalRows": 2,
  "totalCols": 5,
  "dataGrid": [
    [
      "",
      "",
      "Measures",
      "Market",
      "Scenario"
    ],
    [
      "Product",
      "Year",
      "105522.0",
      "",
      ""
    ]
  ],
  "dataGridMetaData": [
    [
      2,
      2,
      0,
      0,
      0
    ],
    [
      0,
      0,
      1,
      2,
      2
    ]
  ],
  "selectedRanges": []
}


###
POST http://localhost:8080/essbase/essbaseUserOptions HTTP/1.1
Content-Type: application/json

{
    "repeatLabel": false,
    "suppressMissingRows": false,
    "suppressZeroRows": false,
    "suppressMissingColumns": false,
    "suppressZeroColumns": false,
    "preseveFormatting": false,
    "adjustColumnWidth": false,
    "indentationGroupVal": "totals",
    "noDataMissingInputVal": "#Missing",
    "noAccessInputVal": "",
    "undoRedoCountInputVal": "5",
    "userId": "chaitanyashree786@gmail.com"
}

###
GET  http://localhost:8080/essbase/essbaseUserOptions HTTP/1.1
